apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: airflow-flower
  ports:
    - name: airflow-flower
      protocol: TCP
      port: 5555
      targetPort: 5555
