apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: default
type: Opaque
stringData:
    WWW_PASSWORD_KEY: www1
    WWW_USER_KEY: www
    FLOWER_BASIC_AUTH_KEY: www:www1
    FERNET_KEY_KEY: DypRbK_RoWa2VYBIEWz8Oldn9YVU9WldXwa7nShZvM4=
    CELERY_BROKER_URL_KEY: redis://default:redis1@redis-service:6379/0
    SQL_ALCHEMY_CONN_KEY: postgresql+psycopg2://airflow:airflow1@postgres-service/airflow
    CELERY_RESULT_BACKEND_KEY: db+postgresql://airflow:airflow1@postgres-service/airflow
