apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-volume
  namespace: default
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/sorriso/Documents/GitHub/kube-airflow-src-ubi8-min/volume/dags"
  capacity:
    storage: 1Gi
  claimRef:
    name: airflow-dags-volume-claim
    namespace: default
