apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: airflow-webserver
  ports:
    - name: airflow-gui
      protocol: TCP
      port: 8080
      targetPort: 8080
